### ISSUE TITLE
where to install V-HACD?

### ISSUE THREAD

**Issue by wjbaibai** [BerkeleyAutomation/meshpy#2]
while I want to use sdf writer, The error comes out:

ERROR:root:Output mesh file /home/angela/Documents/code/preprocess/tmp/tmp_vhacd.obj not found. V-HACD failed. Is V-HACD installed?

where to install V-HACD

**Comment by jeffmahler** [comment]
@wjbaibai Sorry for the delay! I was traveling.

What was the fix for this? I think it is easiest to install V-HACD from [my fork](https://github.com/jeffmahler/v-hacd).
