### ISSUE TITLE
Unable to install Meshpy in python 3.6.5

### ISSUE THREAD

**Issue by monikrish2605** [BerkeleyAutomation/meshpy#6]
I am getting following error while installing meshpy
My python version is 
conda version : 4.5.11
    conda-build version : 3.10.5
         python version : 3.6.5.final.0

+++++++++++++++++++++++++++
(base) C:\Users\Krishna>pip install meshpy
Collecting meshpy
  Using cached https://files.pythonhosted.org/packages/90/03/3bb205ac46141074aeb561f5bbf60fb2214380aa6ac1435b49d275cf219a/MeshPy-2018.2.1.tar.gz
Requirement already satisfied: pytools>=2011.2 in c:\users\krishna\anaconda3\lib\site-packages (from meshpy) (2018.5.2)
Requirement already satisfied: pytest>=2 in c:\users\krishna\anaconda3\lib\site-packages (from meshpy) (3.5.1)
Requirement already satisfied: numpy in c:\users\krishna\anaconda3\lib\site-packages (from meshpy) (1.14.3)
Requirement already satisfied: gmsh_interop in c:\users\krishna\anaconda3\lib\site-packages (from meshpy) (2017.1)
Requirement already satisfied: six in c:\users\krishna\anaconda3\lib\site-packages (from meshpy) (1.11.0)
Requirement already satisfied: decorator>=3.2.0 in c:\users\krishna\anaconda3\lib\site-packages (from pytools>=2011.2->meshpy) (4.3.0)
Requirement already satisfied: appdirs>=1.4.0 in c:\users\krishna\anaconda3\lib\site-packages (from pytools>=2011.2->meshpy) (1.4.3)
Requirement already satisfied: py>=1.5.0 in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (1.5.3)
Requirement already satisfied: setuptools in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (39.1.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (18.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (0.6.0)
Requirement already satisfied: colorama in c:\users\krishna\anaconda3\lib\site-packages (from pytest>=2->meshpy) (0.3.9)
Building wheels for collected packages: meshpy
  Running setup.py bdist_wheel for meshpy ... error
  Complete output from command c:\users\krishna\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Krishna\\AppData\\Local\\Temp\\pip-install-a4ozfv50\\meshpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Krishna\AppData\Local\Temp\pip-wheel-bn3dzzlz --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\meshpy
  copying meshpy\common.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\geometry.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\gmsh.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\gmsh_reader.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\naca.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\ply.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\tet.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\tools.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\triangle.py -> build\lib.win-amd64-3.6\meshpy
  copying meshpy\__init__.py -> build\lib.win-amd64-3.6\meshpy
  running build_ext
  building 'meshpy._internals' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  creating build\temp.win-amd64-3.6\Release\src\cpp
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DEXTERNAL_TEST=1 -DANSI_DECLARATORS=1 -DTRILIBRARY=1 -Ic:\users\krishna\anaconda3\Include -IC:\Users\Krishna\AppData\Roaming\Python\Python36\Include -Isrc/cpp -Ic:\users\krishna\anaconda3\include -Ic:\users\krishna\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpsrc/cpp/wrapper.cpp /Fobuild\temp.win-amd64-3.6\Release\src/cpp/wrapper.obj /EHsc /DVERSION_INFO=\"2018.2.1\"
  wrapper.cpp
  src/cpp/wrapper.cpp(1): fatal error C1083: Cannot open include file: 'pybind11/pybind11.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for meshpy
  Running setup.py clean for meshpy
Failed to build meshpy
Installing collected packages: meshpy
  Running setup.py install for meshpy ... error
    Complete output from command c:\users\krishna\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Krishna\\AppData\\Local\\Temp\\pip-install-a4ozfv50\\meshpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Krishna\AppData\Local\Temp\pip-record-m_tdkp27\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\meshpy
    copying meshpy\common.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\geometry.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\gmsh.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\gmsh_reader.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\naca.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\ply.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\tet.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\tools.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\triangle.py -> build\lib.win-amd64-3.6\meshpy
    copying meshpy\__init__.py -> build\lib.win-amd64-3.6\meshpy
    running build_ext
    building 'meshpy._internals' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DEXTERNAL_TEST=1 -DANSI_DECLARATORS=1 -DTRILIBRARY=1 -Ic:\users\krishna\anaconda3\Include -IC:\Users\Krishna\AppData\Roaming\Python\Python36\Include -Isrc/cpp -Ic:\users\krishna\anaconda3\include -Ic:\users\krishna\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpsrc/cpp/wrapper.cpp /Fobuild\temp.win-amd64-3.6\Release\src/cpp/wrapper.obj /EHsc /DVERSION_INFO=\"2018.2.1\"
    wrapper.cpp
    src/cpp/wrapper.cpp(1): fatal error C1083: Cannot open include file: 'pybind11/pybind11.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\krishna\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Krishna\\AppData\\Local\\Temp\\pip-install-a4ozfv50\\meshpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Krishna\AppData\Local\Temp\pip-record-m_tdkp27\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Krishna\AppData\Local\Temp\pip-install-a4ozfv50\meshpy\
+++++++++++++++++++++++++++++

Please help me out in resolving issue

**Comment by monikrish2605** [comment]
Hi Team,
please help me on this topic

**Comment by jeffmahler** [comment]
Very sorry for my delay in replying. This library is deprecated in favor of [meshrender](https://github.com/BerkeleyAutomation/meshrender) but we no longer maintain public dex-net so there is an old dependency.

Unfortunately, Python 3+ will not be supported for meshpy.

**Comment by monikrish2605** [comment]
Thanks lot for info. Is there any other alternative ?
